//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaArs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliado
    {
        public int Id_Afiliados { get; set; }
        public string Nombres_Afiliados { get; set; }
        public string Apellidos_Afiliados { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<double> MConsumido { get; set; }
        public string Id_Estatus { get; set; }
        public string Id_Plan { get; set; }
    
        public virtual Estatu Estatu { get; set; }
        public virtual Plane Plane { get; set; }
    }
}
