//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaArs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Afiliados_Adrian_PadillaEntities : DbContext
    {
        public Afiliados_Adrian_PadillaEntities()
            : base("name=Afiliados_Adrian_PadillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliado> Afiliados { get; set; }
        public virtual DbSet<Estatu> Estatus { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
    }
}
